# Generated by Django 2.1.2 on 2018-10-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoDwldURL', models.CharField(default='https://www.youtube.com/watch?v=x-gfkXu8OpI', max_length=100)),
                ('summarizeType', models.CharField(choices=[('LR', 'Lex Rank'), ('LU', 'Luhn'), ('LS', 'LSA'), ('TR', 'Text Rank'), ('ED', 'Edmundson')], default='LR', max_length=2)),
                ('summarizationTime', models.DecimalField(decimal_places=0, default=60, max_digits=4)),
                ('bonusWordsFile', models.FileField(default='dummy.txt', upload_to='documents/')),
                ('stigmaWordsFile', models.FileField(default='dummy.txt', upload_to='documents/')),
            ],
        ),
    ]
