# Generated by Django 2.1.2 on 2018-10-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subSummarize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='videoDwldURL',
            field=models.CharField(default='https://www.youtube.com/watch?v=2iOlM9XdOYo', max_length=100),
        ),
    ]
