# Generated by Django 2.1.2 on 2018-10-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subSummarize', '0002_auto_20181021_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='videoDwldURL',
            field=models.CharField(default='https://www.youtube.com/watch?v=X0lXytdjzQo', max_length=100),
        ),
    ]
