# Generated by Django 2.1.2 on 2018-10-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181020_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='videoDwldURL',
            field=models.CharField(default='https://www.youtube.com/watch?v=x-gfkXu8OpI', max_length=100),
        ),
    ]
