# Generated by Django 2.1.2 on 2018-10-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_document_videodwldurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='bonusWordsFile',
        ),
        migrations.RemoveField(
            model_name='document',
            name='stigmaWordsFile',
        ),
        migrations.RemoveField(
            model_name='document',
            name='subtitleFile',
        ),
        migrations.RemoveField(
            model_name='document',
            name='summarizationTime',
        ),
        migrations.RemoveField(
            model_name='document',
            name='summarizeType',
        ),
        migrations.RemoveField(
            model_name='document',
            name='videoFile',
        ),
    ]
