# Generated by Django 2.1.2 on 2018-10-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181020_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fileUpload',
        ),
        migrations.AddField(
            model_name='document',
            name='bonusWordsFile',
            field=models.FileField(default='documents/defaultBonusWords.txt', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='stigmaWordsFile',
            field=models.FileField(default='documents/defaultStigmaWords.txt', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='subtitleFile',
            field=models.FileField(default='documents/defaultBonusWords.txt', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='summarizationTime',
            field=models.DecimalField(decimal_places=0, default=60, max_digits=4),
        ),
        migrations.AddField(
            model_name='document',
            name='summarizeType',
            field=models.CharField(choices=[('LR', 'Lex Rank'), ('LU', 'Luhn'), ('LS', 'LSA'), ('TR', 'Text Rank'), ('ED', 'Edmundson')], default='LR', max_length=2),
        ),
        migrations.AddField(
            model_name='document',
            name='videoDwldURL',
            field=models.CharField(default='https://www.youtube.com/watch?v=x-gfkXu8OpI', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='videoFile',
            field=models.FileField(default='documents/defaultBonusWords.txt', upload_to='documents/'),
        ),
    ]
