# Generated by Django 2.1.2 on 2018-10-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181020_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='videoDwldURL',
        ),
    ]
