# Generated by Django 2.1.2 on 2018-11-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181020_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombineMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexRank', models.BooleanField(default=True)),
                ('luhn', models.BooleanField(default=False)),
                ('lsa', models.BooleanField(default=False)),
                ('textRank', models.BooleanField(default=False)),
            ],
        ),
    ]
