# Generated by Django 2.1.2 on 2018-11-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_combinemethods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombineMethods',
        ),
    ]
