# Generated by Django 2.1.2 on 2018-11-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_combinemethods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LR', models.FloatField()),
                ('LU', models.FloatField()),
                ('LS', models.FloatField()),
                ('TR', models.FloatField()),
                ('ED', models.FloatField()),
            ],
        ),
    ]
