# Generated by Django 2.1.2 on 2018-11-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='ED',
        ),
        migrations.AlterField(
            model_name='document',
            name='summarizeType',
            field=models.CharField(choices=[('LR', 'Lex Rank'), ('LU', 'Luhn'), ('LS', 'LSA'), ('TR', 'Text Rank')], default='LR', max_length=2),
        ),
    ]
